### ISSUE TITLE
Running the visual 

### ISSUE THREAD

**Issue by arshiaesll** [Healthcare-Robotics/bodies-at-rest#10]
Hi, when I try to see the visual of the data set I run into this error.
<img width="623" alt="Screenshot 2023-03-09 102558" src="https://user-images.githubusercontent.com/91429018/224072489-4aca874b-9d9e-47ee-aed0-3335f55e17e1.png">

**Comment by henryclever** [comment]
Hi,

Thanks for the inquiry. Unfortunately, this is a python 2 repo. This is because it includes a patch file for running with Flex, and my python bindings for Flex were for python2. So I kept everything in python2. If you want to create a new branch for python3 and modify things so it's python3 compatible, I would be happy to review it and include it in the repo. But you'll have to fix these print statements among other things ... 

-Henry
